title: Ncasa
baseURL: https://ncasa.it
languageCode: en-us
theme: gohugo-theme-ananke
resourceDir: ../resources
DefaultContentLanguage: en
#SectionPagesMenu: main
Paginate: 3
googleAnalytics: 'G-X3133B55BH'
enableRobotsTXT: yes
languages:
  en:
    contentDir: content/en
    title: Ncasa
    weight: 1
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
params:
  author: 'N. Casarin'
  background_color_class: bg-black
  description: "That's a description, don't think so"
  favicon: ''
  featured_image: /images/back.jpg
  github: ''
  linkedin: ''
  recent_posts_number: 2
  rss: ''
  site_logo: ''
  slack: ''
  stackoverflow: ''
  twitter: 'https://twitter.com/RafanoPiccante'
markup.highlight:
  codeFences : true
  hl_Lines : ""
  lineNoStart : 1
  lineNos : false
  lineNumbersInTable : true
  noClasses : true
  style : "solarized-dark"
  tabWidth : 4
menu:
  main:
  - identifier: about
    name: About
    title: About
    url: /about/
    weight: -100
  - identifier: r
    name: Rstudio
    title: Rstudio
    url: /r/
    weight: -115
  - identifier: article
    name: Article
    title: Article
    url: /article/
    toc: TRUE
    weight: -120
